export const diagramDesignKinds = [
  "architecture", "it-state", "flowchart", "sequence", "state", "er",
  "timeline", "swimlane", "quadrant", "radar", "polar", "loop", "nested",
  "tree", "org-chart", "layers", "venn", "pyramid", "bar", "waterfall", "treemap",
  "line", "gantt", "scatter", "high-level", "process", "medallion",
  "data-flow", "dp-integration", "dp-security-matrix", "sankey", "fishbone",
  "wardley", "kanban", "journey", "deployment", "dependency", "uml-class",
  "story-map", "db-schema",
];

// `custom` is for a purposeful, self-contained HTML visual that does not map to a
// named grammar. Named kinds remain useful metadata even when their visual is
// authored as HTML rather than generated by Aurelius.
export const supportedDiagramKinds = new Set([...diagramDesignKinds, "canvas", "custom"]);
export const nativeDiagramKinds = new Set(["architecture", "canvas"]);

export function diagramKindLabel(kind) {
  return String(kind).split("-").map((part) => part.toUpperCase()).join(" · ");
}

export function validateAccessibleSvg(raw, diagram) {
  const svg = String(raw).replace(/^\s*<\?xml[^>]*>\s*/i, "").trim();
  if (!/^<svg\b/i.test(svg) || !/<\/svg>\s*$/i.test(svg)) {
    throw new Error("Artefato SVG inválido em " + diagram.svgSource);
  }
  const forbidden = /<!doctype|<!entity|<\s*(script|foreignObject|iframe|object|embed|audio|video)\b|\son[a-z]+\s*=|@import/i;
  if (forbidden.test(svg)) {
    throw new Error("Artefato SVG contém conteúdo externo ou executável: " + diagram.svgSource);
  }
  const idValues = [...svg.matchAll(/\bid\s*=\s*["']([^"']+)["']/gi)].map((match) => match[1]);
  const ids = new Set(idValues);
  if (ids.size !== idValues.length) {
    throw new Error("Artefato SVG contém IDs duplicados: " + diagram.svgSource);
  }

  const referenceAssignments = [...svg.matchAll(/\b(?:(?:xlink:)?href|src)\s*=/gi)];
  const referenceAttributes = [...svg.matchAll(/\b(?:(?:xlink:)?href|src)\s*=\s*(["'])([\s\S]*?)\1/gi)];
  if (referenceAssignments.length !== referenceAttributes.length) {
    throw new Error("Artefato SVG contém referência href/src sem aspas: " + diagram.svgSource);
  }
  for (const match of referenceAttributes) {
    const reference = match[2].trim();
    if (!/^#[A-Za-z_][\w:.-]*$/.test(reference) || !ids.has(reference.slice(1))) {
      throw new Error("Artefato SVG contém referência href/src externa ou inexistente: " + diagram.svgSource);
    }
  }
  for (const match of svg.matchAll(/url\s*\(\s*(["']?)([^)'"\s]+)\1\s*\)/gi)) {
    const reference = match[2];
    if (!/^#[A-Za-z_][\w:.-]*$/.test(reference) || !ids.has(reference.slice(1))) {
      throw new Error("Artefato SVG contém referência url() externa ou inexistente: " + diagram.svgSource);
    }
  }
  const opening = svg.match(/^<svg\b([^>]*)>/i)?.[0] || "";
  if (!/\bviewBox\s*=\s*["'][^"']+["']/i.test(opening)) {
    throw new Error("Artefato SVG precisa declarar viewBox: " + diagram.svgSource);
  }
  const labelledBy = opening.match(/\baria-labelledby\s*=\s*["']([^"']+)["']/i)?.[1]?.trim().split(/\s+/) || [];
  if (!/\brole\s*=\s*["']img["']/i.test(opening) || labelledBy.length < 2) {
    throw new Error("Artefato SVG precisa de role=img e aria-labelledby: " + diagram.svgSource);
  }
  const accessibleStart = svg.match(/^<svg\b[^>]*>\s*<title\b([^>]*)>[^<]+<\/title>\s*<desc\b([^>]*)>[^<]+<\/desc>/i);
  const titleId = accessibleStart?.[1]?.match(/\bid\s*=\s*["']([^"']+)["']/i)?.[1];
  const descriptionId = accessibleStart?.[2]?.match(/\bid\s*=\s*["']([^"']+)["']/i)?.[1];
  if (!titleId || !descriptionId) {
    throw new Error("Artefato SVG precisa começar com title e desc identificados: " + diagram.svgSource);
  }
  if (!labelledBy.includes(titleId) || !labelledBy.includes(descriptionId)) {
    throw new Error("aria-labelledby precisa referenciar o title e o desc do SVG: " + diagram.svgSource);
  }
  return /\bclass\s*=/i.test(opening)
    ? svg.replace(/^<svg\b([^>]*?)class=(["'])(.*?)\2/i, '<svg$1class=$2artifact-diagram $3$2')
    : svg.replace(/^<svg\b/i, '<svg class="artifact-diagram"');
}
